scalaStewardArgs:
  - --workspace
  - /var/scala-steward/workspace
  - --repos-file
  - /opt/scala-steward/repos.md
  - --forge-api-host
  - https://api.github.com
  - --git-ask-pass
  - /opt/scala-steward/password.sh
  - --scalafix-migrations
  - /opt/scala-steward/scalafix.conf
  - --do-not-fork

additionalScalaStewardArgs:
  - --git-author-email
  - MY_EMAIL
  - --forge-login
  - MY_LOGIN

additionalScalaStewardEnvs: {}
repos: []
scalafixConfig: |
  disableDefaults = false
  migrations = []

gitSecret: ""
existingGitSecretName: ""

image:
  tag: 0.30.2
  repository: fthomas/scala-steward
  pullPolicy: IfNotPresent

schedule: "@daily"
concurrencyPolicy: "Forbid"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

persistence:
  enabled: true
  className: ""
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 5Gi

additionalFiles: {}
# this can be used to make files available in the container, e. g. for authentication for an artifact repository
# additionalFiles:
#   nexusCredentials:
#     path: /root/.sbt/1.0/credentials.sbt
#     content: |
#       credentials += Credentials(sys.env("NEXUS_REALM"), sys.env("NEXUS_HOST"), sys.env("NEXUS_USERNAME"), sys.env("NEXUS_PASSWORD"))
