apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "scala-steward.fullname" . }}
  labels:
    {{- include "scala-steward.labels" . | nindent 4 }}
spec:
  schedule: "{{- .Values.schedule -}}"
  concurrencyPolicy: "{{- .Values.concurrencyPolicy -}}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: "{{- include "scala-steward.fullname" . -}}"
            image: "{{- .Values.image.repository -}}:{{- .Values.image.tag -}}"
            imagePullPolicy: "{{- .Values.image.pullPolicy -}}"
            resources:
{{ toYaml .Values.resources | indent 14 }}
            args:
            {{- range .Values.scalaStewardArgs }}
            - {{ . }}
            {{- end }}
            {{- range .Values.additionalScalaStewardArgs }}
            - {{ . }}
            {{- end }}
            env:
              - name: GIT_PASS
                valueFrom:
                  secretKeyRef:
                    name: {{ if .Values.existingGitSecretName }}
                          {{- .Values.existingGitSecretName | quote -}}
                          {{- else -}}
                          "{{- include "scala-steward.fullname" . -}}-secret"
                          {{- end }}
                    key: gitSecret
{{- if .Values.additionalScalaStewardEnvs }}
{{ toYaml .Values.additionalScalaStewardEnvs | indent 14 }}
{{- end }}
            volumeMounts:
              - mountPath: /opt/scala-steward
                name: opt
              - mountPath: /var/scala-steward/workspace
                name: workspace
              {{- range $k, $v := .Values.additionalFiles }}
              - mountPath: {{ $v.path }}
                name: files
                subPath: {{ $k }}
              {{- end }}
          volumes:
            - name: opt
              configMap:
                name: {{ include "scala-steward.fullname" . }}-configmap
                items:
                  - key: repos.md
                    path: repos.md
                  - key: scalafix.conf
                    path: scalafix.conf
                  - key: password.sh
                    path: password.sh
                    mode: 0777
            {{- if .Values.persistence.enabled }}
            - name: workspace
              persistentVolumeClaim:
                claimName: {{ include "scala-steward.pvcName" . }}
            {{- else }}
            - name: workspace
              emptyDir: {}
            {{- end }}
            {{- if .Values.additionalFiles }}
            - name: files
              configMap:
                name: {{ include "scala-steward.fullname" . }}-files
                items:
                {{- range $k, $v := .Values.additionalFiles }}
                  - key: {{ $k }}
                    path: {{ $k }}
                {{- end }}
            {{- end }}
